### ISSUE TITLE
Annotation import/export

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlasPipeline/neuroglancer#1]
This neuroglancer poject has the ability to import and export annotations in a CSV format. Let's see if we can merge this feature into ours.
https://github.com/braincogs/neuroglancer

**Comment by Junjie-Cheng** [comment]
Hi @eddyod 

I just finished cherry-picking the commits related to the csv export/import to our repository in the branch `csv`. I also build the neuroglancer with all new features and placed it under `/ng_csv`. I manually tested csv import/export as well as the other features locally and on server (`/ng_csv`), and all features worked fine.

Please have a look at the `ng_csv` version and if everything looks fine we can move it to production and close the issue.

---

Below is just some documentations/findings when I was doing the merge. Documenting them here for future reference.

My initial attempt was to simply merge the branch `BrainCOGS/neuroglancer:exportCSV`, however, there were way too many conflicts because both of us were changing code heavily on several files, especially `src/neuroglancer/ui/annotations.ts`. The upstream from google also changed quite a lot in that file which makes things much more complicated.

Another finding is that `BrainCOGS` repository also contains lots of code specific to their data (e.g. they declared some specific types which leads to some special behaviors), and merging the branch will carry those code (which was useless to us) to our repo. So the only way to merge the feature was to `cherry-pick` each commit related to csv and resolve any possible conflicts. It took more time than expected because I need to build and test (and debug) whenever a commit leads to a conflict to our/google's code.

Our repo seems to have the same problem which may make it harder for others to utilize some features of our code. I am also trying to find a good practice to resolve this (this will be very low-priority).
