### ISSUE TITLE
Feature import annotations

### ISSUE THREAD

**Issue by Junjie-Cheng** [ActiveBrainAtlasPipeline/neuroglancer#13]
Required by users: Functionality to import annotations that already exists in some other URLs (i.e. states stored in the database). The following APIs are provided by @eddyod 
`https://activebrainatlas.ucsd.edu/activebrainatlas/annotation/[id]/[layer_name]`, which returns the annotations in the corresponding layer, in JSON format.
`https://activebrainatlas.ucsd.edu/activebrainatlas/annotations`, which returns the list of all annotation layers that we have in the database.

**Comment by austinhoag** [comment]
Hi @Junjie-Cheng, I'm the author of the Braincogs neuroglancer fork. Ed and I have been discussing how to integrate our two forks into a single one since we are working on a lot of common features. I think you guys have done way more work than me so I am happy to start working off of your fork. I just started adopting the REST API, for example. I also found your recent histogram feature quite helpful. 

I just tried to pull your latest commit: 34795b54db0967412533586cc9cfc79f0f432dd1 to test out the annotation fetching feature and found that I couldn't compile the code due to a missing file: `neuroglancer/widget/fetch_annotation.ts`. I'm happy to test out this and other features in the future, and I plan to make some PRs of some of my other features that we could both use to reduce the work on your end of cherry picking. 

Austin

**Comment by Junjie-Cheng** [comment]
Hi @austinhoag ,

Thanks for contacting us! If you do not mind you can check this repository: `git@github.com:Junjie-Cheng/neuroglancer.git`. I have been working on a better organized repository in terms of commits and history, but unfortunately I did not find a good chance to get this version into the ActiveBrainAtlasPipeline repository. Please also note that there are slight differences between these two repositories, and they have totally different git commit tree.

You should be able to pull/merge any branch without any conflicts as they are based on the Google's commit tree, and they are all independent to each other. That being said, please be careful when dealing with the `backend` branch - we have integrated the API URLs in our code and there may or may not be documentations in the commit message. Also, we DID NOT upload the `firebase.ts` file to the repository as it contains credentials that may expose us to traffic attacks - this will result compilation errors if you simply pull/merge this branch and build without the `firebase.ts` file. For this branch, you can utilize `git cherry-pick` to get the functionalities that you may want.
